### ISSUE TITLE
Appends autocompletion result to input

### ISSUE THREAD

**Issue by rosshadden** [haifengkao/nfasd#1]
Great tool!  I found that when I autocomplete something, the input text remains in the prompt.

For example:

``` sh
v foo<TAB>
# becomes
v foo /tmp/foobar.txt
```

**Comment by haifengkao** [comment]
That's the expected behavior. `foo` will be ignored.
I don't know how to remove the input text. If you do, please send a pull request :)

**Comment by rawsp33d** [comment]
Haha okay.  If I get time this week I'll experiment a bit.

**Comment by haifengkao** [comment]
I have fixed it in https://github.com/haifengkao/nfasd/commit/0189533239adceb2c6af1f0fd2b024f560bf254e

**Comment by rawsp33d** [comment]
Awesome! I like the way you handled the change---it's very scalable.

**Comment by haifengkao** [comment]
what scalable?

**Comment by rawsp33d** [comment]
Using python-argcomplete for completions.  But I guess you were doing that before this, too.
